#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.db import models
from datetime import datetime
import time
class List(models.Model):
    name = models.CharField(max_length=30,primary_key=True,verbose_name='任务名称')
    ips = models.TextField(verbose_name='IPS')
    osuser = models.CharField(max_length=20,verbose_name='系统账号')
    ospwd = models.CharField(max_length=35,verbose_name='系统密码')
    osarch = models.CharField(max_length=20,verbose_name='系统平台')
    osbreed = models.CharField(max_length=20,verbose_name='系统流派')
    osrelease = models.CharField(max_length=20,verbose_name='系统版本')
    ospart = models.TextField(verbose_name='系统分区')
    ospackages = models.TextField(verbose_name='系统软件')
    osenv = models.CharField(max_length=35,verbose_name='任务场景')
    notice_mail = models.EmailField(max_length=254,verbose_name='通知邮箱')
    drive_path = models.URLField(max_length=200,verbose_name='驱动路径')
    raid = models.CharField(max_length=300,verbose_name='RAID配置')
    start_time = models.CharField(max_length=20,default=time.time,verbose_name='开始时间')
    usetime= models.CharField(max_length=30,verbose_name='已用时间')
    status = models.CharField(max_length=30,verbose_name='状态|进度')
    owner = models.CharField(max_length=30,verbose_name='创建者')
    flag = models.CharField(max_length=20,verbose_name='标记')
class Detail(models.Model):
    name = models.CharField(max_length=30,verbose_name='任务名称')
    ip = models.GenericIPAddressField(verbose_name='IP')
    mac = models.CharField(max_length=55,verbose_name='MAC')
    netmask = models.CharField(max_length=55,default='255.255.255.0',verbose_name='NETMASK')
    gateway = models.GenericIPAddressField(default='N/R',verbose_name='网关')
    ipmi_ip = models.GenericIPAddressField(default='N/R',verbose_name='IPMI地址')
    vendor = models.CharField(max_length=50,default='N/R',verbose_name='厂商')
    hardware_model= models.CharField(max_length=50,verbose_name='硬件型号')
    hardware_sn = models.CharField(max_length=150,verbose_name='序列号')
    apply_template= models.CharField(max_length=50,verbose_name='应用模板')
    start_time = models.CharField(max_length=20,default=time.time,verbose_name='开始时间')
    usetime= models.CharField(max_length=30,verbose_name='已用时间')
    status = models.TextField(verbose_name='状态|进度')
    owner = models.CharField(max_length=30,verbose_name='创建者')
    flag = models.CharField(max_length=20,verbose_name='标记')
    class Meta:
        unique_together=("name","ip")

class Users(models.Model):
    employee_id = models.CharField(max_length=30,verbose_name='员工ID')
    username = models.CharField(max_length=30,verbose_name='用户名',unique=True)
    password = models.CharField(max_length=50,verbose_name='密码')
    email = models.CharField(max_length=30,null=True,verbose_name='邮箱',unique=True)
    telephone = models.CharField(max_length=30,null=True,verbose_name='手机号')
    name = models.CharField(max_length=50,verbose_name='姓名')
    last_login = models.DateTimeField(verbose_name='上次登录')
    is_superuser = models.CharField(max_length=20,verbose_name='管理员')
    is_active = models.CharField(max_length=20,verbose_name='账号状态')
    is_online = models.CharField(max_length=20,verbose_name='在线状态')
    registry_time = models.DateTimeField(default=datetime.now,verbose_name='注册时间')
class Groups(models.Model):
    name = models.CharField(max_length=30,verbose_name='角色名称')
    desc = models.CharField(max_length=150,null=True,verbose_name='描述信息')
class Rights(models.Model):
    name = models.CharField(max_length=50,verbose_name='权限名称',unique=True)
    menu1_title = models.CharField(max_length=50,verbose_name='一级菜单名称')
    menu1_icon = models.CharField(max_length=50,verbose_name='一级菜单图标')
    menu2_title = models.CharField(max_length=50,verbose_name='二级菜单名称',unique=True)
    menu2_url = models.CharField(max_length=150,verbose_name='二级菜单url',unique=True)
    desc = models.CharField(max_length=150,verbose_name='描述信息',null=True)
class User_Group(models.Model):
    user = models.ForeignKey("Users",to_field="id",default=1,on_delete=models.CASCADE,verbose_name='用户ID')
    group = models.ForeignKey("Groups",to_field="id",default=1,on_delete=models.CASCADE,verbose_name='角色ID')
    class Meta:
        unique_together=("user","group")

class Group_Right(models.Model):
    group = models.ForeignKey("Groups",to_field="id",default=1,on_delete=models.CASCADE,verbose_name='角色ID')
    right = models.ForeignKey("Rights",to_field="id",default=1,on_delete=models.CASCADE,verbose_name='权限ID')
    class Meta:
        unique_together=("group","right")
class User_Right(models.Model):
    user = models.ForeignKey("Users",to_field="id",default=1,on_delete=models.CASCADE,verbose_name='用户ID')
    right = models.ForeignKey("Rights",to_field="id",default=1,on_delete=models.CASCADE,verbose_name='权限ID')
    class Meta:
        unique_together=("user","right")

class Ip_Sn(models.Model):
    ip = models.GenericIPAddressField(verbose_name='业务IP',null=True)
    sn = models.CharField(max_length=150,verbose_name='序列号',null=True)
    class Meta:
        unique_together=("ip","sn")
class Ip_Sn_Temp(models.Model):
    ip = models.GenericIPAddressField(verbose_name='业务IP')
    sn = models.CharField(max_length=150,verbose_name='序列号')
    num_items = models.CharField(max_length=10,verbose_name='Ip_Sn表总条目数')
class App(models.Model):
    ip = models.GenericIPAddressField(primary_key=True,verbose_name='业务IP')
    osrelease = models.CharField(max_length=100,verbose_name='操作系统',null=True)
    ipmi_ip = models.GenericIPAddressField(verbose_name='IPMI地址',null=True)
    monitor = models.CharField(max_length=100,verbose_name='监控系统',null=True)
    app_level_1 = models.CharField(max_length=200,verbose_name='一级业务系统',null=True)
    app_level_2 = models.CharField(max_length=200,verbose_name='二级业务系统',null=True)
    app_level_3 = models.CharField(max_length=200,verbose_name='三级业务系统',null=True)
    #设备类型：物理机、虚拟机
    device_type  = models.CharField(max_length=100,verbose_name='设备类型',null=True)
    order_ops_user = models.CharField(max_length=100,verbose_name='结算运维接口人',null=True)
    ops_user = models.CharField(max_length=100,verbose_name='运维接口人',null=True)
    ops_team = models.CharField(max_length=100,verbose_name='运维团队',null=True)
    dev_user = models.CharField(max_length=100,verbose_name='开发接口人',null=True)
    dev_team = models.CharField(max_length=100,verbose_name='开发团队',null=True)
    app_user = models.CharField(max_length=100,verbose_name='业务接口人',null=True)
    app_dept = models.CharField(max_length=100,verbose_name='业务部门',null=True)
    #CDN设备：是/否
    is_cdn = models.CharField(max_length=10,verbose_name='CDN设备',null=True)
    #环境：生产环境、测试环境、预览环境
    environment = models.CharField(max_length=10,verbose_name='环境',null=True)
    life_cycle_status = models.CharField(max_length=10,verbose_name='生命周期状态',null=True)
class App_Temp(models.Model):
    ip = models.CharField(max_length=10,verbose_name='业务IP')
    osrelease = models.CharField(max_length=10,verbose_name='操作系统')
    ipmi_ip = models.GenericIPAddressField(verbose_name='IPMI地址')
    monitor = models.CharField(max_length=100,verbose_name='监控系统',null=True)
    app_level_1 = models.CharField(max_length=10,verbose_name='一级业务系统')
    app_level_2 = models.CharField(max_length=10,verbose_name='二级业务系统')
    app_level_3 = models.CharField(max_length=10,verbose_name='三级业务系统')
    device_type  = models.CharField(max_length=10,verbose_name='设备类型')
    order_ops_user = models.CharField(max_length=10,verbose_name='结算运维接口人')
    ops_user = models.CharField(max_length=10,verbose_name='运维接口人')
    ops_team = models.CharField(max_length=10,verbose_name='运维团队')
    dev_user = models.CharField(max_length=10,verbose_name='开发接口人')
    dev_team = models.CharField(max_length=10,verbose_name='开发团队')
    app_user = models.CharField(max_length=10,verbose_name='业务接口人')
    app_dept = models.CharField(max_length=10,verbose_name='业务部门')
    is_cdn = models.CharField(max_length=10,verbose_name='CDN设备')
    environment = models.CharField(max_length=10,verbose_name='环境')
    life_cycle_status = models.CharField(max_length=10,verbose_name='生命周期状态')
    num_items = models.CharField(max_length=10,verbose_name='App表总条目数')
class Hardware(models.Model):
    sn = models.CharField(primary_key=True,max_length=100,verbose_name='序列号')
    model = models.CharField(max_length=100,verbose_name='设备型号',null=True)
    vendor = models.CharField(max_length=100,verbose_name='设备生产商',null=True)
    cpu_model = models.CharField(max_length=100,verbose_name='CPU型号',null=True)
    cpu_core = models.CharField(max_length=100,verbose_name='CPU核数',null=True)
    cpu_fre = models.CharField(max_length=100,verbose_name='CPU主频',null=True)
    memory = models.CharField(max_length=100,verbose_name='内存',null=True)
    net_card = models.CharField(max_length=100,verbose_name='网卡',null=True)
    disk    = models.CharField(max_length=100,verbose_name='硬盘',null=True)
    location = models.CharField(max_length=100,verbose_name='地域',null=True)
    engine_room= models.CharField(max_length=100,verbose_name='机房',null=True)
    rack= models.CharField(max_length=100,verbose_name='机柜',null=True)
    u_site = models.CharField(max_length=100,verbose_name='U位',null=True)
    #是否采购维保：是/否
    order_maintenance = models.CharField(max_length=100,verbose_name='是否采购维保',null=True)
    maintenance_start_time = models.CharField(max_length=50,verbose_name='维保开始时间',null=True)
    maintenance_end_time = models.CharField(max_length=50,verbose_name='维保结束时间',null=True)
    maintenance_vendor = models.CharField(max_length=100,verbose_name='维保厂家',null=True)
    project_name= models.CharField(max_length=100,verbose_name='项目名称',null=True)
    project_code= models.CharField(max_length=100,verbose_name='项目编号',null=True)
    asset_tag = models.CharField(max_length=100,verbose_name='资产编号',null=True)
    uplink= models.CharField(max_length=100,verbose_name='上连架顶',null=True)
class Hardware_Temp(models.Model):
    sn = models.CharField(max_length=10,verbose_name='序列号')
    model = models.CharField(max_length=10,verbose_name='设备型号')
    vendor = models.CharField(max_length=10,verbose_name='设备生产商')
    cpu_model = models.CharField(max_length=10,verbose_name='CPU型号')
    cpu_core = models.CharField(max_length=10,verbose_name='CPU核数')
    cpu_fre = models.CharField(max_length=10,verbose_name='CPU主频')
    memory = models.CharField(max_length=10,verbose_name='内存')
    net_card = models.CharField(max_length=10,verbose_name='网卡')
    disk    = models.CharField(max_length=10,verbose_name='硬盘')
    location = models.CharField(max_length=10,verbose_name='地域')
    engine_room= models.CharField(max_length=10,verbose_name='机房')
    rack= models.CharField(max_length=10,verbose_name='机柜')
    u_site = models.CharField(max_length=10,verbose_name='U位')
    order_maintenance = models.CharField(max_length=10,verbose_name='是否采购维保')
    maintenance_start_time = models.CharField(max_length=10,verbose_name='维保开始时间')
    maintenance_end_time = models.CharField(max_length=10,verbose_name='维保结束时间')
    maintenance_vendor = models.CharField(max_length=10,verbose_name='维保厂家')
    project_name= models.CharField(max_length=10,verbose_name='项目名称')
    project_code= models.CharField(max_length=10,verbose_name='项目编号')
    asset_tag = models.CharField(max_length=10,verbose_name='资产编号')
    uplink= models.CharField(max_length=10,verbose_name='上连架顶')
    num_items = models.CharField(max_length=10,verbose_name='Hardware表总条目数')
class Script(models.Model):
    name = models.CharField(max_length=30,verbose_name='名称')
    content = models.TextField(verbose_name='内容')
    lang = models.CharField(max_length=100,verbose_name='脚本语言')
    desc = models.TextField(verbose_name='描述',null=True)
    create_time = models.CharField(max_length=100,verbose_name='创建时间')
    owner = models.CharField(max_length=100,verbose_name='创建者')
class Host_Group(models.Model):
    name = models.CharField(max_length=30,verbose_name='名称')
    content = models.TextField(verbose_name='内容')
    desc = models.TextField(verbose_name='描述',null=True)
    create_time = models.CharField(max_length=100,verbose_name='创建时间')
    owner = models.CharField(max_length=100,verbose_name='创建者')
class Batch(models.Model):
    name = models.CharField(max_length=30,verbose_name='名称',primary_key=True,)
    ips = models.TextField(verbose_name='IPS')
    command = models.TextField(verbose_name='命令')
    osuser = models.CharField(max_length=20,verbose_name='系统账号')
    ospwd = models.CharField(max_length=35,verbose_name='系统密码')
class Virt_Host(models.Model):
    ip = models.GenericIPAddressField(verbose_name='IP')
    username = models.CharField(max_length=100,verbose_name='用户名')
    password = models.CharField(max_length=100,verbose_name='密码')
    desc = models.CharField(max_length=150,verbose_name='描述信息',null=True)
class Ip_Pool(models.Model):
    name = models.CharField(max_length=50,verbose_name='名称')
    used = models.CharField(max_length=20,verbose_name='已分配')
    unuse= models.CharField(max_length=100,verbose_name='可用')
    desc = models.TextField(verbose_name='描述',null=True)
    create_time = models.CharField(max_length=100,verbose_name='创建时间')
    owner = models.CharField(max_length=100,verbose_name='创建者')
class Login_Log(models.Model):
    login_time = models.CharField(max_length=100,verbose_name='登录时间')
    user = models.CharField(max_length=100,verbose_name='用户')
    status = models.TextField(verbose_name='状态',null=True)
class Manual_Log(models.Model):
    name = models.CharField(max_length=50,verbose_name='名称')
    manual_time = models.CharField(max_length=100,verbose_name='时间')
    action = models.CharField(max_length=100,verbose_name='操作')
    user = models.CharField(max_length=100,verbose_name='用户')
    desc = models.TextField(verbose_name='描述',null=True)




